import type { MetricDef } from './types';

export const NHS_METRICS: MetricDef[] = [
  {
    id: 'nhs-4hr',
    name: 'A&E 4-hour standard',
    description:
      'Percentage of patients attending A&E who are admitted, transferred or discharged within 4 hours of arrival.',
    unit: '%',
    targetValue: 95,
    targetLabel: 'NHSE standard',
    targetDirection: 'higher',
    ragRuleId: '',
    dataSourceHint: 'ED system extract / ECDS',
    reviewFrequency: 'weekly',
  },
  {
    id: 'nhs-rtt',
    name: 'RTT 18-week incomplete',
    description:
      'Percentage of patients on an incomplete referral-to-treatment pathway waiting 18 weeks or less.',
    unit: '%',
    targetValue: 92,
    targetLabel: 'NHSE standard',
    targetDirection: 'higher',
    ragRuleId: '',
    dataSourceHint: 'PAS / RTT system extract',
    reviewFrequency: 'monthly',
  },
  {
    id: 'nhs-cancer-62',
    name: 'Cancer 62-day standard',
    description:
      'Percentage of patients starting cancer treatment within 62 days of an urgent GP referral.',
    unit: '%',
    targetValue: 85,
    targetLabel: 'NHSE standard',
    targetDirection: 'higher',
    ragRuleId: '',
    dataSourceHint: 'Cancer Waiting Times (CWT) system',
    reviewFrequency: 'monthly',
  },
  {
    id: 'nhs-cancer-31',
    name: 'Cancer 31-day standard',
    description: 'Percentage of patients receiving first definitive treatment within 31 days of decision to treat.',
    unit: '%',
    targetValue: 96,
    targetLabel: 'NHSE standard',
    targetDirection: 'higher',
    ragRuleId: '',
    dataSourceHint: 'Cancer Waiting Times (CWT) system',
    reviewFrequency: 'monthly',
  },
  {
    id: 'nhs-cdiff',
    name: 'C. difficile cases',
    description:
      'Number of Clostridium difficile infection cases attributed to this organisation (post-72-hour cases).',
    unit: 'cases',
    targetValue: 0,
    targetLabel: 'Zero tolerance',
    targetDirection: 'lower',
    ragRuleId: '',
    dataSourceHint: 'Infection prevention team / IPCAS',
    reviewFrequency: 'monthly',
  },
  {
    id: 'nhs-mrsa',
    name: 'MRSA bacteraemia cases',
    description: 'Number of MRSA bloodstream infection cases attributed to this organisation.',
    unit: 'cases',
    targetValue: 0,
    targetLabel: 'Zero tolerance',
    targetDirection: 'lower',
    ragRuleId: '',
    dataSourceHint: 'Infection prevention team / IPCAS',
    reviewFrequency: 'monthly',
  },
  {
    id: 'nhs-sickness',
    name: 'Staff sickness absence rate',
    description: 'Percentage of available working days lost to staff sickness absence.',
    unit: '%',
    targetValue: null,
    targetLabel: 'Local target',
    targetDirection: 'lower',
    ragRuleId: '',
    dataSourceHint: 'ESR / HR system',
    reviewFrequency: 'monthly',
  },
  {
    id: 'nhs-vacancy',
    name: 'Staff vacancy rate',
    description: 'Percentage of funded posts that are currently vacant.',
    unit: '%',
    targetValue: null,
    targetLabel: 'Local target',
    targetDirection: 'lower',
    ragRuleId: '',
    dataSourceHint: 'ESR / HR system',
    reviewFrequency: 'monthly',
  },
  {
    id: 'nhs-fft',
    name: 'FFT recommend rate',
    description:
      "Percentage of patients who would recommend this service to friends and family (Friends and Family Test).",
    unit: '%',
    targetValue: null,
    targetLabel: 'National average',
    targetDirection: 'higher',
    ragRuleId: '',
    dataSourceHint: 'FFT system / NHS Fingertips',
    reviewFrequency: 'monthly',
  },
  {
    id: 'nhs-hsmr',
    name: 'HSMR',
    description:
      'Hospital Standardised Mortality Ratio — ratio of observed to expected in-hospital deaths, adjusted for case mix. A value of 100 means mortality is as expected nationally.',
    unit: '',
    targetValue: 100,
    targetLabel: 'National expected (100)',
    targetDirection: 'lower',
    ragRuleId: '',
    dataSourceHint: 'Dr Foster / NHS Benchmarking Network',
    reviewFrequency: 'quarterly',
  },
  {
    id: 'nhs-delayed-discharge',
    name: 'Delayed transfers of care',
    description: 'Number of bed days lost to delayed discharge from hospital, by reason.',
    unit: 'bed days',
    targetValue: null,
    targetLabel: 'Local trajectory',
    targetDirection: 'lower',
    ragRuleId: '',
    dataSourceHint: 'Discharge team / DTOC return',
    reviewFrequency: 'weekly',
  },
  {
    id: 'nhs-readmission',
    name: '30-day emergency readmission rate',
    description: 'Percentage of patients readmitted as an emergency within 30 days of discharge.',
    unit: '%',
    targetValue: null,
    targetLabel: 'Local target',
    targetDirection: 'lower',
    ragRuleId: '',
    dataSourceHint: 'PAS / SUS',
    reviewFrequency: 'monthly',
  },
];
